#!/bin/bash
# System Information Script
# Author : Saniya Sanjiv Patil (24bcs10246)

# ---------- variables ----------
CURRENT_DATE=$(date)
HOST_NAME=$(hostname)
USER_NAME=$(whoami)

echo "=============================================="
echo "        SYSTEM INFORMATION REPORT"
echo "=============================================="

echo "Current Date : $CURRENT_DATE"
echo "Hostname     : $HOST_NAME"
echo "Username     : $USER_NAME"

echo ""
echo "----------- Disk Usage (df -h) -----------"
df -h

echo ""
echo "----------- Running Processes (top 10) -----------"
ps aux | head -n 11

# ---------- user input ----------
echo ""
read -p "Enter a directory name to create: " DIR_NAME
read -p "Enter a file name to create inside it: " FILE_NAME

# ---------- mkdir + touch ----------
mkdir -p "$DIR_NAME"
echo "Directory '$DIR_NAME' created."

touch "$DIR_NAME/$FILE_NAME"
echo "File '$DIR_NAME/$FILE_NAME' created."

# ---------- output redirection ----------
ps aux > "$DIR_NAME/$FILE_NAME"
echo "Running processes saved to '$DIR_NAME/$FILE_NAME' ($(wc -l < "$DIR_NAME/$FILE_NAME") lines)."

echo "=============================================="
echo "Report generated by $USER_NAME on $HOST_NAME"
echo "=============================================="
