apiVersion: v1
kind: Service
metadata:
  name: session16-app
  namespace: s16-cicd
spec:
  type: NodePort
  selector:
    app: session16-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31600
