apiVersion: v1
kind: Service
metadata:
  name: session17-devsecops
  namespace: s17-devsecops
spec:
  type: NodePort
  selector:
    app: session17-devsecops
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 31700
