apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskboard.name" . }}-config
  labels: {{- include "taskboard.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "taskboard.name" . }}-postgres
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
